export const UTRPC = 'UTRPC';

export const CODE_TIMEOUT = 'TIMEOUT';
export const CODE_INTERNAL_ERROR = 'INTERNAL_ERROR';
export const CODE_NOT_FOUND = 'NOT_FOUND';
export const CODE_BAD_REQUEST = 'BAD_REQUEST';
export const CODE_PARSE_ERROR = 'PARSE_ERROR';
export const CODE_INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

export const ACTION_EVENT = '_UTRPC_E';
export const ACTION_REQUEST = '_UTRPC_REQ';
export const ACTION_RECEIVER = '_UTRPC_REC';
export const ACTION_RESPONDER = '_UTRPC_RES';
export const ACTION_SUBSCRIPTION_START = '_UTRPC_SUB_START';
export const ACTION_SUBSCRIPTION_STOP = '_UTRPC_SUB_STOP';